#!/bin/bash

# change file title top metadata title

# TODO
# Use rename util instead of mv, can't get mv to work
# The code aboce this to grab meta data works fine
# Need to Trim the title grabbed from exiftool and remove spaces, ' , etc.. maybe use sed to do this.
# Estasblish a naming convention that can be applied to all (Episode Number and title, No date)

for file in ~/Music/chapo/*;
do
	# Grabs Full path of file
	filename=$(echo ${file%.*})
 	# Grabs just the extension
	ext="${file##*.}"
 	# Grabs title according to MetaData
	trueTitle=$(exiftool $file -title -p '$title' )
	# Display Info Gathered

	echo "FileName: $filename"
	echo "Extension: $ext"
	echo "Meta Title: $trueTitle"
done



# testt=$(echo $trueTitle | tr ' ' '_' | tr '-' '_')

# newName=$testt.$ext

# echo $newName





